# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/huffman_coder_acc/huffman_coder_acc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc || ORIG_REF_NAME==huffman_coder_acc} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_processing_system7_0_0/huffman_coder_acc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_processing_system7_0_0 || ORIG_REF_NAME==huffman_coder_acc_processing_system7_0_0} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_huff_coder4_0_0/huffman_coder_acc_huff_coder4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_huff_coder4_0_0 || ORIG_REF_NAME==huffman_coder_acc_huff_coder4_0_0} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_ps7_0_axi_periph_1/huffman_coder_acc_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_ps7_0_axi_periph_1 || ORIG_REF_NAME==huffman_coder_acc_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_rst_ps7_0_100M_1/huffman_coder_acc_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_rst_ps7_0_100M_1 || ORIG_REF_NAME==huffman_coder_acc_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_ila_0_0/huffman_coder_acc_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_ila_0_0 || ORIG_REF_NAME==huffman_coder_acc_ila_0_0} -quiet] -quiet

# IP: bd/huffman_coder_acc/ip/huffman_coder_acc_auto_pc_0/huffman_coder_acc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==huffman_coder_acc_auto_pc_0 || ORIG_REF_NAME==huffman_coder_acc_auto_pc_0} -quiet] -quiet

# XDC: bd/huffman_coder_acc/huffman_coder_acc_ooc.xdc
