webtalk_init -webtalk_dir F:\\MAGISTERKA_S1\\SDUP\\PROJEKT_HUFFMAN_V2\\project_1\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-06-01 22:17:30" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3vdk93hkkt1shpjckmrc5jlmg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.477 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1622554700676" -context "sdk\\\\bsp/1622554700676"
webtalk_add_data -client sdk -key hwid -value "1622542267991" -context "sdk\\\\bsp/1622554700676"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1622554700676"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1622554700676"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1622554700676"
webtalk_add_data -client sdk -key uid -value "1622554709362" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key hwid -value "1622542267991" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key bspid -value "1622554700676" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1622554709362"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key DebugCount -value "28" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key PerfCount -value "1" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1622578650889"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1622578650889"
webtalk_transmit -clientid 911424068 -regid "" -xml F:\\MAGISTERKA_S1\\SDUP\\PROJEKT_HUFFMAN_V2\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\MAGISTERKA_S1\\SDUP\\PROJEKT_HUFFMAN_V2\\project_1\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\MAGISTERKA_S1\\SDUP\\PROJEKT_HUFFMAN_V2\\project_1\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
