# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/MAGISTERKA_S1/SDUP/PROJEKT_HUFFMAN_V2/project_1/project_1.srcs/sources_1/bd/huffman_coder_acc/ip/huffman_coder_acc_processing_system7_0_0/huffman_coder_acc_processing_system7_0_0.xci
# IP: The module: 'huffman_coder_acc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MAGISTERKA_S1/SDUP/PROJEKT_HUFFMAN_V2/project_1/project_1.srcs/sources_1/bd/huffman_coder_acc/ip/huffman_coder_acc_processing_system7_0_0/huffman_coder_acc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'huffman_coder_acc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/MAGISTERKA_S1/SDUP/PROJEKT_HUFFMAN_V2/project_1/project_1.srcs/sources_1/bd/huffman_coder_acc/ip/huffman_coder_acc_processing_system7_0_0/huffman_coder_acc_processing_system7_0_0.xci
# IP: The module: 'huffman_coder_acc_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/MAGISTERKA_S1/SDUP/PROJEKT_HUFFMAN_V2/project_1/project_1.srcs/sources_1/bd/huffman_coder_acc/ip/huffman_coder_acc_processing_system7_0_0/huffman_coder_acc_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'huffman_coder_acc_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
